version: '2'

services:
  web:
    image: bdwilliams/rethinkdb-simple-app
    restart: always
    environment:
      - APP_PORT=8000
      - RETHINKDB_HOST=dbmaster
    networks:
      - front
      - back
    ports:
      - "8000"

networks:
  front:
    driver: overlay
  back:
    driver: overlay