version: "2"

services:
  lb:
    image: hanzel/load-balancing-swarm
    container_name: lb
    networks:
      - app
    ports:
      - "80:80"
    environment:
      - APP_NAME=nginx_web
      - CONSUL_URL=${CONSUL_MASTER}:8500
    depends_on:
     - web
  web:
    image: nginx:stable-alpine
    restart: always
    networks:
      - app
    ports:
      - "80"
      - "443"

networks:
  app:
    driver: overlay
