version: "2"

services:
  consul:
    container_name: consul-master
    restart: always
    command: -server -client 0.0.0.0 -bootstrap --data-dir /var/consul -ui
    image: gliderlabs/consul-agent:0.6
    ports:
      - 8301:8301
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
      - 53:53/udp