version: '2'

services:
  postgres-slave:
    restart: always
    image: sameersbn/postgresql:9.4-18
    ports:
      - "5432"
    environment:
      REPLICATION_MODE: slave
      REPLICATION_USER: repluser
      REPLICATION_PASS: repluserpass
      REPLICATION_HOST: dbmaster
      SERVICE_NAME: dbslave
    # volume_driver: convoy
    # volumes:
    #    - dbdata:/tmp/test123
    networks:
      - back

networks:
  back:
    driver: overlay

volumes:
  dbdata:
    driver: convoy
